export const COMMITMENTS_SEED = [
  { number: 1, title: 'Universal design, offline-capable',
    body: 'Every product works flawlessly on fiber and on intermittent 2G. Same features, same quality. Connectivity is not a gatekeeper.' },
  { number: 2, title: 'Simplicity standard',
    body: 'If a grade-8 student cannot complete a core workflow in 5 minutes without training, the feature is not finished.' },
  { number: 3, title: 'Fair, transparent pricing',
    body: 'A free-forever tier enough to run a one-person business. Published prices. No "contact sales." No per-seat gouging.' },
  { number: 4, title: 'All modules, every tier',
    body: 'AI, multi-store, fraud detection, analytics, integrations — standard features, not enterprise add-ons.' },
  { number: 5, title: 'Local languages and formats',
    body: 'Multilingual by default. Your language, your currency, your date format, your cultural norms.' },
  { number: 6, title: 'Open source where possible',
    body: 'Knowledge belongs to humanity, not shareholders. Core tooling is open and forkable by any developer anywhere.' },
  { number: 7, title: 'AI-augmented lean operations',
    body: 'A small, remote, AI-assisted team keeps overhead low. The savings fund real democratization, not executive salaries.' },
  { number: 8, title: 'Environmental sustainability',
    body: 'Paperless by default. Energy-efficient. Green-hosted. One planet, one standard, for the generations that follow.' },
  { number: 9, title: 'Interplanetary-ready',
    body: 'Technology that serves humanity beyond Earth must first serve every human on Earth. No one left behind.' },
];
