/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'product-categories': ProductCategory;
    products: Product;
    'commitment-items': CommitmentItem;
    'timeline-events': TimelineEvent;
    'legal-pages': LegalPage;
    'contact-routes': ContactRoute;
    redirects: Redirect;
    'release-notes': ReleaseNote;
    'roadmap-items': RoadmapItem;
    'journal-posts': JournalPost;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'commitment-items': CommitmentItemsSelect<false> | CommitmentItemsSelect<true>;
    'timeline-events': TimelineEventsSelect<false> | TimelineEventsSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    'contact-routes': ContactRoutesSelect<false> | ContactRoutesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'release-notes': ReleaseNotesSelect<false> | ReleaseNotesSelect<true>;
    'roadmap-items': RoadmapItemsSelect<false> | RoadmapItemsSelect<true>;
    'journal-posts': JournalPostsSelect<false> | JournalPostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'zh-CN' | 'es' | 'hi' | 'ar' | 'fr' | 'pt' | 'bn' | 'ru' | 'ur' | 'id' | 'sw' | 'yo' | 'ha')
    | ('en' | 'zh-CN' | 'es' | 'hi' | 'ar' | 'fr' | 'pt' | 'bn' | 'ru' | 'ur' | 'id' | 'sw' | 'yo' | 'ha')[];
  globals: {
    'site-settings': SiteSetting;
    'homepage-content': HomepageContent;
    'manifesto-page': ManifestoPage;
    'about-page': AboutPage;
    'green-page': GreenPage;
    'contact-page': ContactPage;
    'itu-data': ItuDatum;
    'status-page': StatusPage;
    'trust-page': TrustPage;
    'help-page': HelpPage;
    'careers-page': CareersPage;
    'press-page': PressPage;
    'security-page': SecurityPage;
    'pricing-page': PricingPage;
    'faq-page': FaqPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'homepage-content': HomepageContentSelect<false> | HomepageContentSelect<true>;
    'manifesto-page': ManifestoPageSelect<false> | ManifestoPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'green-page': GreenPageSelect<false> | GreenPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'itu-data': ItuDataSelect<false> | ItuDataSelect<true>;
    'status-page': StatusPageSelect<false> | StatusPageSelect<true>;
    'trust-page': TrustPageSelect<false> | TrustPageSelect<true>;
    'help-page': HelpPageSelect<false> | HelpPageSelect<true>;
    'careers-page': CareersPageSelect<false> | CareersPageSelect<true>;
    'press-page': PressPageSelect<false> | PressPageSelect<true>;
    'security-page': SecurityPageSelect<false> | SecurityPageSelect<true>;
    'pricing-page': PricingPageSelect<false> | PricingPageSelect<true>;
    'faq-page': FaqPageSelect<false> | FaqPageSelect<true>;
  };
  locale: 'en' | 'zh-CN' | 'es' | 'hi' | 'ar' | 'fr' | 'pt' | 'bn' | 'ru' | 'ur' | 'id' | 'sw' | 'yo' | 'ha';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  ordering: number;
  accentColor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  /**
   * If the product is publicly known by a different name (e.g. ClapMove → "Joint Exercise"), enter it here. Otherwise leave blank.
   */
  publicName?: string | null;
  category: number | ProductCategory;
  tagline?: string | null;
  shortDescription?: string | null;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  universalReachNote?: string | null;
  outboundURL: string;
  productStatus: 'production' | 'staging' | 'awaiting-approval' | 'infrastructure';
  /**
   * Marks the 5 products shown on the homepage: Clappe, ClapBill, Clapwork, ClapDiet, ClapMove.
   */
  isFlagship?: boolean | null;
  launchDate?: string | null;
  icon?: (number | null) | Media;
  ordering: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commitment-items".
 */
export interface CommitmentItem {
  id: number;
  number: number;
  title: string;
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events".
 */
export interface TimelineEvent {
  id: number;
  date: string;
  title: string;
  description?: string | null;
  media?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  slug: 'privacy' | 'terms' | 'accessibility' | 'cookies';
  title: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  lastUpdated: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-routes".
 */
export interface ContactRoute {
  id: number;
  slug: 'general' | 'press' | 'partnerships' | 'legal';
  label: string;
  /**
   * This email is never rendered publicly — used only as the SMTP recipient.
   */
  forwardTo: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  statusCode: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "release-notes".
 */
export interface ReleaseNote {
  id: number;
  slug: string;
  version: string;
  releaseDate: string;
  gitTag: string;
  gitSha: string;
  title: string;
  summary?: string | null;
  changes?:
    | {
        type: 'added' | 'changed' | 'fixed' | 'removed' | 'security';
        entry: string;
        id?: string | null;
      }[]
    | null;
  authors?:
    | {
        username: string;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published';
  ordering?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap-items".
 */
export interface RoadmapItem {
  id: number;
  slug: string;
  title: string;
  summary: string;
  category: 'website' | 'products' | 'infra' | 'accessibility' | 'green';
  status: 'planned' | 'in-progress' | 'shipped' | 'paused' | 'cancelled';
  targetQuarter?: string | null;
  shippedAt?: string | null;
  gitRefs?:
    | {
        ref: string;
        id?: string | null;
      }[]
    | null;
  ordering: number;
  whyItMatters?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts".
 */
export interface JournalPost {
  id: number;
  slug: string;
  title: string;
  subtitle?: string | null;
  author: number | User;
  publishedAt: string;
  updatedAt: string;
  readingTime?: number | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  sources: {
    label: string;
    href: string;
    id?: string | null;
  }[];
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  coverImage?: (number | null) | Media;
  status: 'draft' | 'published' | 'unlisted';
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'commitment-items';
        value: number | CommitmentItem;
      } | null)
    | ({
        relationTo: 'timeline-events';
        value: number | TimelineEvent;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'contact-routes';
        value: number | ContactRoute;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'release-notes';
        value: number | ReleaseNote;
      } | null)
    | ({
        relationTo: 'roadmap-items';
        value: number | RoadmapItem;
      } | null)
    | ({
        relationTo: 'journal-posts';
        value: number | JournalPost;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  ordering?: T;
  accentColor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  publicName?: T;
  category?: T;
  tagline?: T;
  shortDescription?: T;
  longDescription?: T;
  universalReachNote?: T;
  outboundURL?: T;
  productStatus?: T;
  isFlagship?: T;
  launchDate?: T;
  icon?: T;
  ordering?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commitment-items_select".
 */
export interface CommitmentItemsSelect<T extends boolean = true> {
  number?: T;
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events_select".
 */
export interface TimelineEventsSelect<T extends boolean = true> {
  date?: T;
  title?: T;
  description?: T;
  media?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  body?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-routes_select".
 */
export interface ContactRoutesSelect<T extends boolean = true> {
  slug?: T;
  label?: T;
  forwardTo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  statusCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "release-notes_select".
 */
export interface ReleaseNotesSelect<T extends boolean = true> {
  slug?: T;
  version?: T;
  releaseDate?: T;
  gitTag?: T;
  gitSha?: T;
  title?: T;
  summary?: T;
  changes?:
    | T
    | {
        type?: T;
        entry?: T;
        id?: T;
      };
  authors?:
    | T
    | {
        username?: T;
        id?: T;
      };
  status?: T;
  ordering?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap-items_select".
 */
export interface RoadmapItemsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  summary?: T;
  category?: T;
  status?: T;
  targetQuarter?: T;
  shippedAt?: T;
  gitRefs?:
    | T
    | {
        ref?: T;
        id?: T;
      };
  ordering?: T;
  whyItMatters?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts_select".
 */
export interface JournalPostsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  subtitle?: T;
  author?: T;
  publishedAt?: T;
  updatedAt?: T;
  readingTime?: T;
  body?: T;
  sources?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  coverImage?: T;
  status?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  studioBlurb: string;
  footerSources?: string | null;
  topBarStatusText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-content".
 */
export interface HomepageContent {
  id: number;
  heroLabel: string;
  heroTagline: string;
  heroCtaPrimary: string;
  heroCtaSecondary: string;
  factsTitle: string;
  factsLead: string;
  flagshipsTitle: string;
  flagshipsLead: string;
  commitmentsTitle: string;
  commitmentsLead: string;
  seeAllPortfolioLine: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifesto-page".
 */
export interface ManifestoPage {
  id: number;
  title: string;
  lead: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  sources?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  title: string;
  lead: string;
  founderStory: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  incorporationContext: string;
  leanOpsPhilosophy: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "green-page".
 */
export interface GreenPage {
  id: number;
  title: string;
  lead: string;
  environmentalStance: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  hostingStory: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  futureGenerationPledge: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Used for carbon calculation. Update when Contabo DC mix is verified.
   */
  hostingGreenRatio: number;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  title: string;
  lead: string;
  privacyNote: string;
  successMessage: string;
  errorMessage: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itu-data".
 */
export interface ItuDatum {
  id: number;
  offlineCount: number;
  onlinePercent: number;
  offlinePercent: number;
  highIncomePercent: number;
  lowIncomePercent: number;
  highIncome5G: number;
  lowIncome5G: number;
  urbanPercent: number;
  ruralPercent: number;
  offlineInLowMiddleIncomePercent: number;
  sourceLabel: string;
  sourceUrl: string;
  lastVerified: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "status-page".
 */
export interface StatusPage {
  id: number;
  kumaBaseUrl: string;
  kumaSlug: string;
  eyebrow?: string | null;
  title: string;
  lede: string;
  groups?:
    | {
        heading: string;
        monitorIds?:
          | {
              monitorId: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  operationalCopy?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-page".
 */
export interface TrustPage {
  id: number;
  eyebrow?: string | null;
  title: string;
  lede: string;
  pillars?:
    | {
        key: 'security' | 'privacy' | 'sustainability' | 'accessibility' | 'finance';
        heading: string;
        blurb: string;
        href: string;
        proof?:
          | {
              label: string;
              value: string;
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  certifications?:
    | {
        name: string;
        issuer: string;
        issuedAt: string;
        evidenceURL: string;
        id?: string | null;
      }[]
    | null;
  dataResidency?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  subprocessors?:
    | {
        name: string;
        purpose: string;
        dataAccessed?: string | null;
        location: string;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  reportIncident?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  lastReviewedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help-page".
 */
export interface HelpPage {
  id: number;
  eyebrow?: string | null;
  title: string;
  lede: string;
  emergencyRow: {
    heading: string;
    body: string;
    href: string;
  };
  routes?:
    | {
        key: string;
        heading: string;
        blurb: string;
        links?:
          | {
              label: string;
              href: string;
              external?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  popularQuestions?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  contactFallback: {
    heading: string;
    body: string;
    href: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page".
 */
export interface CareersPage {
  id: number;
  eyebrow: string;
  title: string;
  lede: string;
  howWeWork?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  productFamily?:
    | {
        name: string;
        line: string;
        id?: string | null;
      }[]
    | null;
  process?:
    | {
        stage: string;
        what: string;
        id?: string | null;
      }[]
    | null;
  openings: {
    heading: string;
    currentlyHiringText: string;
    note: string;
  };
  introduceYourself: {
    eyebrow: string;
    heading: string;
    body: string;
    email: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-page".
 */
export interface PressPage {
  id: number;
  eyebrow: string;
  title: string;
  lede: string;
  factSheet?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  quotes?:
    | {
        text: string;
        who: string;
        role: string;
        id?: string | null;
      }[]
    | null;
  boilerplate: string;
  storyAnglesYes?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  storyAnglesNo?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  brandGuidance: {
    brandName: string;
    founderReference: string;
  };
  contactCta: {
    eyebrow: string;
    heading: string;
    body: string;
    email: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "security-page".
 */
export interface SecurityPage {
  id: number;
  eyebrow: string;
  title: string;
  lede: string;
  postureSummary: {
    eyebrow: string;
    heading: string;
    body: string;
  };
  topStats?:
    | {
        label: string;
        value: string;
        hint: string;
        id?: string | null;
      }[]
    | null;
  posture?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  dataHandling?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  compliance?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  reportCta: {
    eyebrow: string;
    heading: string;
    body: string;
    email: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-page".
 */
export interface PricingPage {
  id: number;
  eyebrow: string;
  title: string;
  lede: string;
  whyThisExists: {
    eyebrow: string;
    heading: string;
    body: string;
    freeTierLine: string;
    paidTierLine: string;
    enterpriseLine: string;
  };
  principles?:
    | {
        label: string;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  antiPatterns?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  workedExample?:
    | {
        who: string;
        tier: string;
        what: string;
        note: string;
        id?: string | null;
      }[]
    | null;
  seePricesCta: {
    eyebrow: string;
    heading: string;
    body: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page".
 */
export interface FaqPage {
  id: number;
  eyebrow: string;
  title: string;
  lede: string;
  sections?:
    | {
        title: string;
        items?:
          | {
              q: string;
              a: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  stillStuckCta: {
    eyebrow: string;
    heading: string;
    body: string;
    email: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  studioBlurb?: T;
  footerSources?: T;
  topBarStatusText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-content_select".
 */
export interface HomepageContentSelect<T extends boolean = true> {
  heroLabel?: T;
  heroTagline?: T;
  heroCtaPrimary?: T;
  heroCtaSecondary?: T;
  factsTitle?: T;
  factsLead?: T;
  flagshipsTitle?: T;
  flagshipsLead?: T;
  commitmentsTitle?: T;
  commitmentsLead?: T;
  seeAllPortfolioLine?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifesto-page_select".
 */
export interface ManifestoPageSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  body?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  founderStory?: T;
  incorporationContext?: T;
  leanOpsPhilosophy?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "green-page_select".
 */
export interface GreenPageSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  environmentalStance?: T;
  hostingStory?: T;
  futureGenerationPledge?: T;
  hostingGreenRatio?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  privacyNote?: T;
  successMessage?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itu-data_select".
 */
export interface ItuDataSelect<T extends boolean = true> {
  offlineCount?: T;
  onlinePercent?: T;
  offlinePercent?: T;
  highIncomePercent?: T;
  lowIncomePercent?: T;
  highIncome5G?: T;
  lowIncome5G?: T;
  urbanPercent?: T;
  ruralPercent?: T;
  offlineInLowMiddleIncomePercent?: T;
  sourceLabel?: T;
  sourceUrl?: T;
  lastVerified?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "status-page_select".
 */
export interface StatusPageSelect<T extends boolean = true> {
  kumaBaseUrl?: T;
  kumaSlug?: T;
  eyebrow?: T;
  title?: T;
  lede?: T;
  groups?:
    | T
    | {
        heading?: T;
        monitorIds?:
          | T
          | {
              monitorId?: T;
              id?: T;
            };
        id?: T;
      };
  operationalCopy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-page_select".
 */
export interface TrustPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lede?: T;
  pillars?:
    | T
    | {
        key?: T;
        heading?: T;
        blurb?: T;
        href?: T;
        proof?:
          | T
          | {
              label?: T;
              value?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  certifications?:
    | T
    | {
        name?: T;
        issuer?: T;
        issuedAt?: T;
        evidenceURL?: T;
        id?: T;
      };
  dataResidency?: T;
  subprocessors?:
    | T
    | {
        name?: T;
        purpose?: T;
        dataAccessed?: T;
        location?: T;
        href?: T;
        id?: T;
      };
  reportIncident?: T;
  lastReviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help-page_select".
 */
export interface HelpPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lede?: T;
  emergencyRow?:
    | T
    | {
        heading?: T;
        body?: T;
        href?: T;
      };
  routes?:
    | T
    | {
        key?: T;
        heading?: T;
        blurb?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              external?: T;
              id?: T;
            };
        id?: T;
      };
  popularQuestions?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  contactFallback?:
    | T
    | {
        heading?: T;
        body?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page_select".
 */
export interface CareersPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lede?: T;
  howWeWork?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  productFamily?:
    | T
    | {
        name?: T;
        line?: T;
        id?: T;
      };
  process?:
    | T
    | {
        stage?: T;
        what?: T;
        id?: T;
      };
  openings?:
    | T
    | {
        heading?: T;
        currentlyHiringText?: T;
        note?: T;
      };
  introduceYourself?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        email?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-page_select".
 */
export interface PressPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lede?: T;
  factSheet?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  quotes?:
    | T
    | {
        text?: T;
        who?: T;
        role?: T;
        id?: T;
      };
  boilerplate?: T;
  storyAnglesYes?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  storyAnglesNo?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  brandGuidance?:
    | T
    | {
        brandName?: T;
        founderReference?: T;
      };
  contactCta?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        email?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "security-page_select".
 */
export interface SecurityPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lede?: T;
  postureSummary?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
      };
  topStats?:
    | T
    | {
        label?: T;
        value?: T;
        hint?: T;
        id?: T;
      };
  posture?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  dataHandling?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  compliance?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  reportCta?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        email?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-page_select".
 */
export interface PricingPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lede?: T;
  whyThisExists?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        freeTierLine?: T;
        paidTierLine?: T;
        enterpriseLine?: T;
      };
  principles?:
    | T
    | {
        label?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  antiPatterns?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  workedExample?:
    | T
    | {
        who?: T;
        tier?: T;
        what?: T;
        note?: T;
        id?: T;
      };
  seePricesCta?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page_select".
 */
export interface FaqPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lede?: T;
  sections?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              q?: T;
              a?: T;
              id?: T;
            };
        id?: T;
      };
  stillStuckCta?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        email?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}